export const CHARACTER_FORM_ADD = 'CHARACTER_FORM_ADD'
export const CHARACTER_FORM_CHANGE = 'CHARACTER_FORM_CHANGE'
export const CHARACTER_FORM_LOADING = 'CHARACTER_FORM_LOADING'
export const CHARACTER_FORM_CLOSE = 'CHARACTER_FORM_CLOSE'
// export const CHARACTER_FORM_DELETE = 'CHARACTER_FORM_DELETE'


export const CHARACTERS_REQUEST_LOADING = 'CHARACTERS_REQUEST_LOADING'
export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST'
export const CHARACTER_REQUEST_ERROR = 'CHARACTER_REQUEST_ERROR'